# Generated by Django 4.2.26 on 2025-11-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_image_news_main_image_newsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='external_link',
            field=models.URLField(blank=True, help_text='Посилання на зовнішню новину', null=True),
        ),
    ]
