# Generated by Django 4.2.26 on 2025-11-24 11:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactpage_internationalpage_projectspage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='internationalpage',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='projectspage',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='statutpage',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='volunteeringpage',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
