# Generated by Django 4.2.26 on 2025-11-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_aboutpage_content_alter_contactpage_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statutpage',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Document (PDF)'),
        ),
        migrations.AddField(
            model_name='statutpage',
            name='document_name',
            field=models.CharField(blank=True, help_text='e.g. Statute of the Organization', max_length=255, null=True, verbose_name='Document Name'),
        ),
    ]
