# Generated by Django 4.2.26 on 2025-11-26 06:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_statutpage_document_statutpage_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='content_uk',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='content_uk',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='title_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='internationalpage',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='internationalpage',
            name='content_uk',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='internationalpage',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internationalpage',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='content_uk',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statutpage',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='statutpage',
            name='content_uk',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='statutpage',
            name='document_name_en',
            field=models.CharField(blank=True, help_text='e.g. Statute of the Organization', max_length=255, null=True, verbose_name='Document Name'),
        ),
        migrations.AddField(
            model_name='statutpage',
            name='document_name_uk',
            field=models.CharField(blank=True, help_text='e.g. Statute of the Organization', max_length=255, null=True, verbose_name='Document Name'),
        ),
        migrations.AddField(
            model_name='statutpage',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statutpage',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='volunteeringpage',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='volunteeringpage',
            name='content_uk',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='volunteeringpage',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='volunteeringpage',
            name='title_uk',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
