# Generated by Django 4.2.26 on 2025-11-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aboutpage_content_en_aboutpage_content_uk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Контакти', 'verbose_name_plural': 'Контакти'},
        ),
        migrations.AlterModelOptions(
            name='internationalpage',
            options={'verbose_name': 'Видання та публікації', 'verbose_name_plural': 'Видання та публікації'},
        ),
        migrations.AlterModelOptions(
            name='projectspage',
            options={'verbose_name': 'Участь у проектах', 'verbose_name_plural': 'Участь у проектах'},
        ),
        migrations.AlterModelOptions(
            name='statutpage',
            options={'verbose_name': 'Міжнародна діяльність', 'verbose_name_plural': 'Міжнародна діяльність'},
        ),
        migrations.AlterModelOptions(
            name='volunteeringpage',
            options={'verbose_name': 'Волонтерство та Освіта', 'verbose_name_plural': 'Волонтерство та Освіта'},
        ),
    ]
